#!/usr/bin/env bash

if [ "$(id -u)" -ne 0 ]; then
	echo "ERROR: You need to be root."
	exit 1
fi

rm /tmp/localestemp.sh* 2> /dev/null
rm /tmp/hosttemp.sh* 2> /dev/null
	
LOCALESTEMP=/tmp/localestemp.sh.$$
HOSTTEMP=/tmp/hosttemp.sh.$$

SUDOUSER=""

function cleanup { rm $LOCALESTEMP; $HOSTTEMP; exit; }

trap cleanup; SIGHUP SIGINT SIGTERM

function core { clear; cover; sleep 1s; verify; packages; hostnamer; localer; newuser; swapper; graphical; aur; ohmyzsh; software; finisher;}

function cover {
	echo '          					    ``...`                                                    '
	echo '                                      `..:/+++/--/shdmmmmmhy+:.`                                              '
	echo '                                  `-+ydmMMMMMMMMMMMMMMMMMMMMMMNds:`                                           '
	echo '                               `/ymMMMMMNmNMMMMMMMMMMMMNhooyNNMMMMmy:`                                        '
	echo '                             -yNMMMMMNy//hMMMMMMMNyymMMMMNdhm-:sNMMMMd/                                       '
	echo '                           .yMMMMMMNo.`oMMMMMMMMod: .ydMMMMMM+.``omMMMMh.                                     '
	echo '                         `oNMMMMMMo` -MMMMMMMMMmdmMNNmyNMMMMMMMNy/`oNMMMN/                                    '
	echo '                        /mMMMMMMs.  oMMMMMMMNo.  :Mo:hMMs:mMMMMNMMmyhMMMMMo-`                                  '
	echo '                      -hMMMMMMy. .sdMMMMMMMh.o/-/sy:+NMNhys+/:-......--:/+oshddyo/-`                           '
	echo '                    `sNMMMMMh: ` +MMMMMMMMo` .dshs yMh.` `.-..               ``-/oydds/.                       '
	echo '                   /mMMMMMm/`  odMMMMMMMm- s::ydomsMy``+o+:-:/++/`                 `./sdds/.                   '
	echo '                 `yMMMMMMs`   -mMMMMMMMh.  +y+/:-hMs `h-       `:y.                    `.+hmh+.               '
	echo '                -dMMMMMm:  `.:NMMMMMMMs` ./hyso/dMo  :y   //:/-  :y                        ./hmh/`            '
	echo '               :mMMMMMd.   `+NMMMMMMN+ .-ohyyhhhMo   `h.  :: `y   N                           .odmo.           '
	echo '              +NMMMMMy`  `./NMMMMMMN/   `+/-:/yMo     .o:.`.-+-  -d                             `/dNs.        '
	echo '             oMMMMMMs`  o-+MMMMMMMN:`::/oo-  +Ms        -----`  -y-                               `oNm/       '
	echo '           `sMMMMMMo   +yoNMMMMMMm-`o/`-oyh`+Ms          `````-oo`                                  -dMy`     '
	echo '          `yMMMMMN/    /yNMMMMMMd. -h--h+-ysMy          `-////:`                                     `dMh`    '
	echo '          yMMMMMN:  -+:oMMMMMMMd````y++o++sNh`                                                        `mMy    '
	echo '        /MMMMMy`   /+ooMMMMMMh`  ./+N:-+oNm`                                                            mMd   '
	echo '       .NMMMMs  `+ +++MMMMMMy   so++s++oNNs+oooo/-       `/oysyyso/.                                    yMM   '
	echo '       dMMMM+    :s `mMMMMMs `o +++o.-:mN.     `-o-     -h+-`   `-/sh+                                  yMM   '
	echo '      /MMMM+  -/o msoMMMMMo   :y `-s-`dN-                            `                                  hMN    '
	echo '      dMMM+   +oooy:mMMMMo ./o`do:+y/yM/                  `:/`                                         `NMh    '
	echo '     /MMMs  --:+s+osMMMM+  :sy/d//+hNM+            `/   .  `:y                                         sMM:    '
	echo '     mMMd` .mss+`hoyMMM+  `./ss++oohMo             .+  `y+/:+:                                        :MMy     '
	echo '    /MMN. o+mhym/yyNMMs  syo+./y. +Ny               -:::. ``                                         :NMd`     '
	echo '    dMM/`-ysoshh.`+MMm``-yhhdohysyMM:                                                               /NMd.      '
	echo '   :MMy.-sd:oy+y.`dMM/ :od+dhs./oNmmNh/.                                                          `oMMs`      '
	echo '   yMN.-/oy.+yys-hMMd -hy:yy+o `dm.`/ymdyysooo+///::--.......................--::////////+++++oooshNmo   	    '
	echo '  `MMy/+yyosy/-/dMMM/:/ss-oys/`dN-    `.--:://++ooosssyyyyyhyyyyhhhhhhhyyyhyyyssoo++++++///////::::-`         '
	echo '  +Mm`.+dy+sy.-mmNMm`.oys/yyo+hN:                                                                             '
	echo '  yMo/m+.`.-o/Nd-MMo+hho:oh``yM/                                                                               '
	echo '  hMd+ysy+:/yMy`:Mm :+ysoo+ yM/                                                                                '
	echo '  yM/h+-h``hMo  +My+d:`- :syM+                                                                                '
	echo '  oMds+ms+Nm-   +Mm/yyd//:hM/                                                                                  '
	echo '  -Mh  :dNs`    /Mod+:h``dN:                                                                                  	'
	echo '   oNdmms.      -Mmhody/mm-                                                                                    '
	echo '    .--`         mN. -yMy.                                                                                     '
	echo '                  /Nhsmd/                                                                                       '
	echo '                  -/+-`                     '
	echo '.oPYo. .oPYo. .pPYo.   .oPYo.                       o   o                 .oPYo.   o              8  o                '
	echo '8  .o8     `8 8        8    8                       8                     8        8              8                   '
	echo '8 .P`8   .oP` 8oPYo.   8      oPYo. .oPYo. .oPYo.  o8P o8 o    o .oPYo.   `Yooo.  o8P o    o .oPYo8 o8 .oPYo. .oPYo.  '
	echo '8.d` 8    `b. 8`  `8   8      8  `` 8oooo8 .oooo8   8   8 Y.  .P 8oooo8       `8   8  8    8 8    8  8 8    8 Yb..   '
	echo '8o`  8     :8 8.  .P   8    8 8     8.     8    8   8   8 `b..d` 8.            8   8  8    8 8    8  8 8    8   `Yb. '
	echo '`YooP` `YooP` `YooP`   `YooP` 8     `Yooo` `YooP8   8   8  `YP`  `Yooo`   `YooP`   8  `YooP` `YooP`  8 `YooP` `YooP. '
	echo ':.....::.....::.....::::.....:..:::::.....::.....:::..::..::...:::.....::::.....:::..::.....::.....::..:.....::.....:'
	echo ':::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::'
	echo ':::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::'
}

function whichverify() {
	stat=$(which "$1" 2>&1)
	if [[ "$stat" =~ which:* ]]; then 
		return 1
	else
		return 0
	fi
}

function verify {
    ARCH=$(uname -m)
    OPERATING=$(uname -o)
	SELECTOR=""
	PI="$(cat /sys/firmware/devicetree/base/model)"

	if [ "$OPERATING" != "GNU/Linux" ]; then
		clear
		echo 'ERROR: Your Operating System is not GNU/Linux, exiting'
		exit 1
	fi

    if [ "$ARCH" != "aarch64" ]; then
        echo "ERROR: This script is only intended to run on aarch64 Devices."
        exit 1
    fi

    if [[ "$PI" =~ ^Raspberry[[:space:]]Pi[[:space:]]4.* ]]; then
        echo "ready" &> /dev/null
	else
		echo "ERROR: This script is only intended to run on Raspberry Pi 4 Devices."
        exit 1
    fi

    SELECTOR="pacman"
	whichverify "$SELECTOR"
	local res=$?

	if [ $res -eq 1 ]; then
		clear
		echo "ERROR: Arch Linux pacman is not available in this system, this system isn't Arch Linux?"
		exit 1
	fi

    PING=$(ping -c 1 8.8.8.8 2>&1) 

    if [[ "$PING" =~ unreachable* ]]; then
		clear
		echo "ERROR: This PC doesn't have internet connection, please check"
		exit 1
	fi

	echo "Populating Arch ARM Keys.."

	pacman-key --init &> /dev/null
	pacman-key --populate archlinuxarm  &> /dev/null

    echo "Updating Arch ARM Repositories..."

    pacman -Sy &> /dev/null

    SELECTOR="lsb_release"
	whichverify "$SELECTOR"
	local res=$?

	if [ $res -eq 1 ]; then
		echo "lsb_release is not available in this system, installing"
		pacman -S lsb-release --noconfirm &> /dev/null
	fi

	IS_ARCH=$(lsb_release -is)

	if [ "$IS_ARCH" != "Arch" ]; then
		clear
		echo "ERROR: Your Operating System is not Arch Linux, exiting"
		exit 1
	fi

	SELECTOR="dialog"
	whichverify "$SELECTOR"
	local res=$?

	if [ $res -eq 1 ]; then
		echo "dialog is not available in this system, installing"
		pacman -S dialog --noconfirm &> /dev/null
	fi

	pacman -S ncurses --noconfirm &> /dev/null

	echo "All dependencies is ok!"

	START=$(date +%s)
	CHARS="/-\|"

	while [[ $(($(date +%s) - START)) -lt 2 ]]; do
		for (( i=0; i<${#CHARS}; i++ )); do
			sleep 0.08
			echo -en "${CHARS:$i:1}" "\r"
		done
	done

}

function packages {
	clear

	echo -e "=============== SYSTEM UPDATE AND INSTALL CORE PACKAGES =============== \n" 

		systemctl enable sshd &> /dev/null
		systemctl start sshd &> /dev/null

		pacman -Syyu --noconfirm 
		pacman -S sudo git wget rsync networkmanager f2fs-tools neofetch \
		screen unrar p7zip vim zsh --noconfirm 
		

	echo -e "=============== OK =============== \n" 
	read -r -p "Press Enter to continue..."

	echo -e "=============== ROOT PASSWORD FOR YOUR SYSTEM =============== \n" 

	passwd

	echo " "
	echo -e "=============== OK =============== \n" 
	read -r -p "Press Enter to continue..."


}

function hostnamer {
	

	clear
	dialog --title "Hostname" \
    --backtitle "036 Creative Studios" \
    --inputbox "Please write your hostname (ex: A036-rpi4)" 8 80 2>"$HOSTTEMP"

    RESPONSE=$?
    DATA=$(<$HOSTTEMP)

    case $RESPONSE in
    0) 
		echo "${DATA}" > /etc/hostname
		echo "127.0.1.1        ${DATA}" >> /etc/hosts
		return;;
    1) 
        clear; exit 0  
        return;;
    255) 
        clear; exit 0
        return;;
    esac
}

function localer {

	clear
	dialog --msgbox "America/Guayaquil is the timezone by default, if you want to change, here is the command\n\n \
		ln -sf /usr/share/zoneinfo/REGION/CITY /etc/localtime" 9 50

	ln -sf /usr/share/zoneinfo/America/Guayaquil /etc/localtime
	hwclock --systohc

	dialog --clear --backtitle "036 Creative Studios" \
		--title "Locale" \
		--menu "Choose your locale, if you want to change to other locales, check the README of the Github of this project" 12 50 4 \
		Spanish "es_ES" \
		English "en_US" 2>"${LOCALESTEMP}"

		menuitem=$(<"${LOCALESTEMP}")

		case $menuitem in
			Spanish) 
				clear
				sed -i 's/^#es_ES.UTF-8 UTF-8/es_ES.UTF-8 UTF-8/' /etc/locale.gen &> /dev/null
				locale-gen
				echo 'LANG="es_ES.UTF-8"' > /etc/locale.conf
				echo 'LC_TIME="es_ES.UTF-8"' >> /etc/locale.conf
				echo 'LANGUAGE="es_EC:es_ES:es"' >> /etc/locale.conf
				return;;
			English) 
				clear
				sed -i 's/^#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen &> /dev/null
				locale-gen
				echo 'LANG="en_US.UTF-8"' > /etc/locale.conf
				echo 'LC_TIME="en_US.UTF-8"' >> /etc/locale.conf
				echo 'LANGUAGE="es_US:en"' >> /etc/locale.conf
				return;;
			*) clear; exit 0;;
		esac
}

function newuser {

	clear
	echo -e "=============== ADD A USER TO A SUDO GROUP =============== \n" 
	
	read -r -p "Write your new user: " SUDOUSER
	useradd --create-home "$SUDOUSER"
	passwd "$SUDOUSER"
	usermod -aG wheel "$SUDOUSER"
	sed -i 's/^#.*%wheel ALL=(ALL) ALL$/%wheel ALL=(ALL) ALL/' /etc/sudoers &> /dev/null

	echo " "
	echo -e "=============== OK =============== \n" 
	read -r -p "Press Enter to continue..."
}

function swapper {

	clear
	echo -e "=============== SWAPPING =============== \n" 

	dd if=/dev/zero of=/swapfile bs=1M count=1024 status=progress
	chmod 600 /swapfile
	mkswap /swapfile
	swapon /swapfile
	echo "swapfile none swap defaults 0 0" >> /etc/fstab
	echo "vm.swappiness=1" >> /etc/sysctl.d/99-sysctl.conf

	
	echo " "
	echo -e "=============== OK =============== \n" 
	read -r -p "Press Enter to continue..."
}

function graphical {

	clear
	dialog --clear --title "Graphical Environment" \
	--backtitle "036 Creative Studios" \
	--menu "Choose a GUI, these are the common used, this script recommends XFCE" 15 50 4 \
			XFCE "Xfce Desktop Environment" \
			GNOME "GNOME Desktop Environment" \
			KDE "KDE Desktop Environment" \
			XORG "Minimal xorg Desktop" \

			NOGUI "No install GUI" 2>"${GRAPHICALTEMP}"

	menuitem=$(<"${GRAPHICALTEMP}")

		case $menuitem in
			XFCE) 

				clear
				echo -e "=============== XFCE =============== \n" 
	
				pacman -S xorg-server xf86-video-fbturbo-git xorg-xinit --noconfirm
				pacman -S xfce4 gdm xfce4-goodies ttf-ubuntu-font-family gtk-engines gtk-engine-murrine \
					gnome-themes-standard xdg-user-dirs ttf-dejavu gvfs xfce4-notifyd network-manager-applet volumeicon --noconfirm
				systemctl enable gdm

				touch /HOME/"$SUDOUSER"/.xinitrc
				echo "export XAUTHORITY=${HOME}/.Xauthority" > /HOME/"$SUDOUSER"/.xinitrc
				echo "exec dbus-run-session -- startxfce4" >> /HOME/"$SUDOUSER"/.xinitrc	

				echo " "
				echo -e "=============== OK =============== \n" 
				read -r -p "Press Enter to continue..."
				return;;

			GNOME) 

				clear
				echo -e "=============== GNOME =============== \n" 
				pacman -S xorg-server xf86-video-fbturbo-git xorg-xinit --noconfirm
				pacman -S gnome gdm gnome-themes-standard network-manager-applet --noconfirm
				systemctl enable gdm

				echo " "
				echo -e "=============== OK =============== \n" 
				read -r -p "Press Enter to continue..."
				return;;

			KDE) 

				clear
				echo -e "=============== KDE =============== \n" 
				pacman -S xorg-server xf86-video-fbturbo-git xorg-xinit --noconfirm
				pacman -S plasma plasma-wayland-session kde-applications network-manager-applet \
					network-manager-applet volumeicon --noconfirm
				systemctl enable sddm.service

				echo " "
				echo -e "=============== OK =============== \n" 
				read -r -p "Press Enter to continue..."
				return;;

			XORG) 

				clear
				echo -e "=============== XORG ONLY =============== \n" 
				pacman -S xorg-server xf86-video-fbturbo-git xorg-xinit --noconfirm

				echo " "
				echo -e "=============== OK =============== \n" 
				read -r -p "Press Enter to continue..."
				return;;

			NOGUI) 
				return;;

			*) clear; exit 0;;
		esac

			clear
			echo -e "=============== BLUETOOTH AND SOUND =============== \n" 

			pacman -S  alsa-utils alsa-firmware alsa-lib alsa-plugins pulseaudio-alsa \
				pulseaudio-bluetooth bluez-utils libmm-glib modemmanager blueman --noconfirm

			sudo systemctl enable ModemManager
			sudo systemctl enable bluetooth
			sudo systemctl start ModemManager
			sudo systemctl start bluetooth

			echo "enable_uart=1" > /boot/config.txt
			echo "dtparam=audio=on" >> /boot/config.txt
			echo "hdmi_drive=2" >> /boot/config.txt
			echo "audio_pwm_mode=2" >> /boot/config.txt
			echo "disable_overscan=1" >> /boot/config.txt
			echo "gpu_mem=64" >> /boot/config.txt
			echo "cma=512" >> /boot/config.txt
			echo "dtoverlay=vc4-fkms-v3d" >> /boot/config.txt
			echo "max_framebuffers=2" >> /boot/config.txt

			echo " "
			echo -e "=============== OK =============== \n" 
			read -r -p "Press Enter to continue..."

}

function aur {

	clear
	echo -e "=============== AUR (YAY ASKS YOU YOUR PASSWORD, PAY ATTENTION) ===============  \n" 

	pacman -S --needed base-devel fakeroot packer go --noconfirm

	sudo -u "$SUDOUSER" bash -c 'cd; git clone https://aur.archlinux.org/yay-bin.git'
	sudo -u "$SUDOUSER" bash -c 'cd; cd yay-bin; makepkg -si'
	sudo -u "$SUDOUSER" bash -c 'cd; rm -rf yay-bin'

	echo " "
	echo -e "=============== OK =============== \n" 
	read -r -p "Press Enter to continue..."

}

function ohmyzsh {

	clear
	echo -e "=============== OMZ =============== \n" 

	touch /home/"$SUDOUSER"/omz.sh

	echo '#!/bin/bash' > /home/"$SUDOUSER"/omz.sh
	echo 'sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"' >> /home/"$SUDOUSER"/omz.sh
	echo 'sed -i -e "s/ZSH_THEME=.*/ZSH_THEME=\"pmcgee\"/" .zshrc' >> /home/"$SUDOUSER"/omz.sh
	echo 'sed -i -e "/^source $ZSH.*/i ZSH_DISABLE_COMPFIX=true" .zshrc' >> /home/"$SUDOUSER"/omz.sh
	echo 'sudo ln -s "$HOME"/.zshrc /root/.zshrc' >> /home/"$SUDOUSER"/omz.sh
	echo 'sudo ln -s "$HOME"/.oh-my-zsh /root/.oh-my-zsh' >> /home/"$SUDOUSER"/omz.sh
	echo 'git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting' >> /home/"$SUDOUSER"/omz.sh
	echo 'git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions' >> /home/"$SUDOUSER"/omz.sh
	echo 'sed -i -e "s/plugins=(.*/plugins=(git zsh-syntax-highlighting zsh-autosuggestions)/" .zshrc' >> /home/"$SUDOUSER"/omz.sh

	chown "$SUDOUSER" /home/"$SUDOUSER"/omz.sh

	echo "We create a script called omz.sh in your home directory, after reboot, use chmod +x at omz.sh"

	echo " "
	echo -e "=============== OK =============== \n" 
	read -r -p "Press Enter to continue..."

}

function software {

	systemctl mask lvm2-monitor

		dialog --title "More Sofware!!" --backtitle "036 Creative Studios" \
		--yesno "This script has a little pack of software, Do you like it?\n \
			-> baobab \n \
			-> ntfs-3g \n \
			-> exfatprogs \n \
			-> exfat-utils \n \
			-> xrdp \n \
			-> xarchiver \n \
			-> xorgxrdp \n \
			-> xorgxrdp \n \
			-> visual-studio-code \n \
			-> rpi-eeprom-git \n \
			-> rpi-imager \n \
			-> box64 \n \
			-> numix-gtk-theme-git\n \
			-> numix-icon-theme \n \
			-> preload " 26 65
	clear
	response=$?

	if [ $response = 0 ]; then
	
	clear
	echo -e "=============== SOFTWARE =============== \n" 

	touch /home/"$SUDOUSER"/software.sh

	echo allowed_users=anybody > /etc/X11/Xwrapper.config

	echo '!#/bin/bash' > /home/"$SUDOUSER"/software.sh
	echo 'yay -S baobab ntfs-3g exfatprogs exfat-utils \' >> /home/"$SUDOUSER"/software.sh
	echo 'xarchiver gparted xrdp \' >> /home/"$SUDOUSER"/software.sh
	echo 'xorgxrdp pi-bluetooth visual-studio-code-bin preload \' >> /home/"$SUDOUSER"/software.sh
	echo 'rpi-eeprom-git rpi-imager box64 \' >> /home/"$SUDOUSER"/software.sh
	echo 'brave-bin exe-thumbnailer github-desktop-bin gobject-introspection libdbusmenu-gtk2 \' >> /home/"$SUDOUSER"/software.sh
	echo 'libdbusmenu-glib libdbusmenu-gtk3 appmenu-gtk-module numix-gtk-theme \' >> /home/"$SUDOUSER"/software.sh
	echo 'numix-icon-theme-git numix-circle-icon-theme-git' >> /home/"$SUDOUSER"/software.sh

	echo 'systemctl enable xrdp' >> /home/"$SUDOUSER"/software.sh
	echo 'systemctl enable xrdp-sesman' >> /home/"$SUDOUSER"/software.sh
	echo 'systemctl enable preload' >> /home/"$SUDOUSER"/software.sh
		
	chown "$SUDOUSER" /home/"$SUDOUSER"/software.sh

	echo "We create a script called software.sh in your home directory, after reboot, use chmod +x at software.sh"

	echo " "
	echo -e "=============== OK =============== \n" 
	read -r -p "Press Enter to continue..."


	elif [ $response -eq 1 ] || [ $response -eq 255 ]; then
		clear
		return
	else
		clear
		exit 0
	fi
}


function finisher {

	clear
	dialog --msgbox 'READY!!!, Your RPI4 is succesfully configured, if you have errors, please report at 036raspberry in GitHub' 7 50
	clear
	echo "Please reboot your rpi4 to make changes"
	exit 0
}

core

[ -f $LOCALESTEMP ] && rm $LOCALESTEMP
[ -f $HOSTTEMP ] && rm $HOSTTEMP