#!/usr/bin/env bash

if [ "$(id -u)" -ne 0 ]; then
	echo "ERROR: You need to be root."
	exit 1
fi

rm /tmp/localestemp.sh* 2> /dev/null
rm /tmp/hosttemp.sh* 2> /dev/null
rm /tmp/graphicaltemp.sh* 2> /dev/null
	
LOCALESTEMP=/tmp/localestemp.sh.$$
HOSTTEMP=/tmp/hosttemp.sh.$$
GRAPHICALTEMP=/tmp/graphicaltemp.sh.$$

SUDOUSER=""

function cleanup { rm $LOCALESTEMP; $HOSTTEMP; $GRAPHICALTEMP exit; }

trap cleanup; SIGHUP SIGINT SIGTERM

function core { clear; cover; sleep 1s; verify; packages; newuser; graphical; ohmyzsh; software; finisher;}

function cover {
	echo '          					    ``...`                                                    '
	echo '                                      `..:/+++/--/shdmmmmmhy+:.`                                              '
	echo '                                  `-+ydmMMMMMMMMMMMMMMMMMMMMMMNds:`                                           '
	echo '                               `/ymMMMMMNmNMMMMMMMMMMMMNhooyNNMMMMmy:`                                        '
	echo '                             -yNMMMMMNy//hMMMMMMMNyymMMMMNdhm-:sNMMMMd/                                       '
	echo '                           .yMMMMMMNo.`oMMMMMMMMod: .ydMMMMMM+.``omMMMMh.                                     '
	echo '                         `oNMMMMMMo` -MMMMMMMMMmdmMNNmyNMMMMMMMNy/`oNMMMN/                                    '
	echo '                        /mMMMMMMs.  oMMMMMMMNo.  :Mo:hMMs:mMMMMNMMmyhMMMMMo-`                                  '
	echo '                      -hMMMMMMy. .sdMMMMMMMh.o/-/sy:+NMNhys+/:-......--:/+oshddyo/-`                           '
	echo '                    `sNMMMMMh: ` +MMMMMMMMo` .dshs yMh.` `.-..               ``-/oydds/.                       '
	echo '                   /mMMMMMm/`  odMMMMMMMm- s::ydomsMy``+o+:-:/++/`                 `./sdds/.                   '
	echo '                 `yMMMMMMs`   -mMMMMMMMh.  +y+/:-hMs `h-       `:y.                    `.+hmh+.               '
	echo '                -dMMMMMm:  `.:NMMMMMMMs` ./hyso/dMo  :y   //:/-  :y                        ./hmh/`            '
	echo '               :mMMMMMd.   `+NMMMMMMN+ .-ohyyhhhMo   `h.  :: `y   N                           .odmo.           '
	echo '              +NMMMMMy`  `./NMMMMMMN/   `+/-:/yMo     .o:.`.-+-  -d                             `/dNs.        '
	echo '             oMMMMMMs`  o-+MMMMMMMN:`::/oo-  +Ms        -----`  -y-                               `oNm/       '
	echo '           `sMMMMMMo   +yoNMMMMMMm-`o/`-oyh`+Ms          `````-oo`                                  -dMy`     '
	echo '          `yMMMMMN/    /yNMMMMMMd. -h--h+-ysMy          `-////:`                                     `dMh`    '
	echo '          yMMMMMN:  -+:oMMMMMMMd````y++o++sNh`                                                        `mMy    '
	echo '        /MMMMMy`   /+ooMMMMMMh`  ./+N:-+oNm`                                                            mMd   '
	echo '       .NMMMMs  `+ +++MMMMMMy   so++s++oNNs+oooo/-       `/oysyyso/.                                    yMM   '
	echo '       dMMMM+    :s `mMMMMMs `o +++o.-:mN.     `-o-     -h+-`   `-/sh+                                  yMM   '
	echo '      /MMMM+  -/o msoMMMMMo   :y `-s-`dN-                            `                                  hMN    '
	echo '      dMMM+   +oooy:mMMMMo ./o`do:+y/yM/                  `:/`                                         `NMh    '
	echo '     /MMMs  --:+s+osMMMM+  :sy/d//+hNM+            `/   .  `:y                                         sMM:    '
	echo '     mMMd` .mss+`hoyMMM+  `./ss++oohMo             .+  `y+/:+:                                        :MMy     '
	echo '    /MMN. o+mhym/yyNMMs  syo+./y. +Ny               -:::. ``                                         :NMd`     '
	echo '    dMM/`-ysoshh.`+MMm``-yhhdohysyMM:                                                               /NMd.      '
	echo '   :MMy.-sd:oy+y.`dMM/ :od+dhs./oNmmNh/.                                                          `oMMs`      '
	echo '   yMN.-/oy.+yys-hMMd -hy:yy+o `dm.`/ymdyysooo+///::--.......................--::////////+++++oooshNmo   	    '
	echo '  `MMy/+yyosy/-/dMMM/:/ss-oys/`dN-    `.--:://++ooosssyyyyyhyyyyhhhhhhhyyyhyyyssoo++++++///////::::-`         '
	echo '  +Mm`.+dy+sy.-mmNMm`.oys/yyo+hN:                                                                             '
	echo '  yMo/m+.`.-o/Nd-MMo+hho:oh``yM/                                                                               '
	echo '  hMd+ysy+:/yMy`:Mm :+ysoo+ yM/                                                                                '
	echo '  yM/h+-h``hMo  +My+d:`- :syM+                                                                                '
	echo '  oMds+ms+Nm-   +Mm/yyd//:hM/                                                                                  '
	echo '  -Mh  :dNs`    /Mod+:h``dN:                                                                                  	'
	echo '   oNdmms.      -Mmhody/mm-                                                                                    '
	echo '    .--`         mN. -yMy.                                                                                     '
	echo '                  /Nhsmd/                                                                                       '
	echo '                  -/+-`                     '
	echo '.oPYo. .oPYo. .pPYo.   .oPYo.                       o   o                 .oPYo.   o              8  o                '
	echo '8  .o8     `8 8        8    8                       8                     8        8              8                   '
	echo '8 .P`8   .oP` 8oPYo.   8      oPYo. .oPYo. .oPYo.  o8P o8 o    o .oPYo.   `Yooo.  o8P o    o .oPYo8 o8 .oPYo. .oPYo.  '
	echo '8.d` 8    `b. 8`  `8   8      8  `` 8oooo8 .oooo8   8   8 Y.  .P 8oooo8       `8   8  8    8 8    8  8 8    8 Yb..   '
	echo '8o`  8     :8 8.  .P   8    8 8     8.     8    8   8   8 `b..d` 8.            8   8  8    8 8    8  8 8    8   `Yb. '
	echo '`YooP` `YooP` `YooP`   `YooP` 8     `Yooo` `YooP8   8   8  `YP`  `Yooo`   `YooP`   8  `YooP` `YooP`  8 `YooP` `YooP. '
	echo ':.....::.....::.....::::.....:..:::::.....::.....:::..::..::...:::.....::::.....:::..::.....::.....::..:.....::.....:'
	echo ':::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::'
	echo ':::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::'
}

function whichverify() {
	stat=$(which "$1" 2>&1)

	if [ "$stat" == "" ]; then
		return 1
	else
		return 0
	fi
}

function verify {
    ARCH=$(uname -m)
    OPERATING=$(uname -o)
	SELECTOR=""
	PI="$(cat /sys/firmware/devicetree/base/model)"

	if [ "$OPERATING" != "GNU/Linux" ]; then
		clear
		echo 'ERROR: Este sistema no es GNU/Linux, saliendo'
		exit 1
	fi

    if [ "$ARCH" != "aarch64" ]; then
        echo "ERROR: This script is only intended to run on aarch64 Devices."
        exit 1
    fi

    if [[ "$PI" =~ ^Raspberry[[:space:]]Pi[[:space:]]4.* ]]; then
        echo "ready" &> /dev/null
	else
		echo "ERROR: Este script sólo se ejecuta en Raspberry Pi 4"
        exit 1
    fi

    SELECTOR="apt"
	whichverify "$SELECTOR"
	local res=$?

	if [ $res -eq 1 ]; then
		clear
		echo "ERROR: APT no está disponible, ¿Acaso esto no es Debian?"
		exit 1
	fi

    SELECTOR="raspi-config"
	whichverify "$SELECTOR"
	local res=$?

	if [ $res -eq 1 ]; then
		clear
		echo "ERROR: Este distro de Debian no tiene la aplicación raspi-config, por favor use Raspberry Pi OS Lite, saliendo"
		exit 1
	fi

	SELECTOR="openbox-lxde-session"
	whichverify "$SELECTOR"
	local res=$?

	if [ $res -eq 0 ]; then
		clear
		echo "ERROR: Ok, is Raspbery Pi OS, but this is not a Raspberry Pi OS Lite, exiting"
		echo "ERROR: Bien, este es Raspberry Pi OS, pero no es Raspberry Pi OS Lite, saliendo"
		exit 1
	fi

    PING=$(ping -c 1 8.8.8.8 2>&1) 

    if [[ "$PING" =~ unreachable* ]]; then
		clear
		echo "ERROR: No tienes conexión a internet, por favor revisa e inténtalo de nuevo"
		exit 1
	fi

    echo "Updating Debian repositories..."
    echo "Actualizando repositorios de Debian..."

    apt update &> /dev/null

    SELECTOR="lsb_release"
	whichverify "$SELECTOR"
	local res=$?

	if [ $res -eq 1 ]; then
		echo "lsb_release no está disponible, instalando"
		pacman -S lsb-release --noconfirm &> /dev/null
	fi

	IS_ARCH=$(lsb_release -is)

	if [ "$IS_ARCH" != "Debian" ]; then
		clear
		echo "ERROR: Tu sistema operativo no es Debian, saliendo"
		exit 1
	fi

	SELECTOR="dialog"
	whichverify "$SELECTOR"
	local res=$?

	if [ $res -eq 1 ]; then
		echo "dialog is no está disponible, instalando"
		apt install -y dialog &> /dev/null
	fi

	echo "Todo ok!"

	START=$(date +%s)
	CHARS="/-\|"

	while [[ $(($(date +%s) - START)) -lt 2 ]]; do
		for (( i=0; i<${#CHARS}; i++ )); do
			sleep 0.08
			echo -en "${CHARS:$i:1}" "\r"
		done
	done

}

function packages {
	clear

	sed -i 's/^#PermitRootLogin\s.*$/PermitRootLogin Yes/' \
	/etc/ssh/sshd_config &> /dev/null

	echo -e "=============== ACTUALIZACIÓN DEL SISTEMA =============== \n" 

	apt upgrade -y
		
	echo -e "=============== OK =============== \n" 
	read -r -p "Presione Enter para continuar..."

	clear

	echo -e "=============== CONTRASEÑA DE ROOT PARA EL SISTEMA =============== \n"  

	passwd

	echo " "
	echo -e "=============== OK =============== \n" 
	read -r -p "Presione Enter para continuar..."
	
	clear

	echo -e "=============== CAMBIO A LOS REPOSITORIOS DE SID Y ACTUALIZACIÓN DE DIST =============== \n" 

	mv /etc/apt/sources.list /etc/apt/sources.list.old
	mv /etc/apt/sources.list.d /etc/apt/sources.list.d.old

	echo "deb http://deb.debian.org/debian sid main contrib non-free" > /etc/apt/sources.list
	echo "deb-src http://deb.debian.org/debian sid main contrib non-free" >> /etc/apt/sources.list

	apt update
	apt dist-upgrade -y

	echo " "
	echo -e "=============== OK =============== \n" 
	read -r -p "Presione Enter para continuar..."

	clear

	echo -e "=============== INSTALACIÓN DE PAQUETES BASE =============== \n" 

	apt install -y cockpit git net-tools wget vim rsync neofetch \
		screen unrar p7zip vim network-manager-gnome zsh

	systemctl enable NetworkManager.service
	echo "Set managed=true" >> /etc/NetworkManager/NetworkManager.conf
	systemctl disable dhcpcd.service

	echo " "
	echo -e "=============== OK =============== \n" 
	read -r -p "Presione Enter para continuar..."

	dialog --msgbox 'La aplicación de raspi-config se va a abrir, por favor cambia las configuraciones pertinentes' 7 50

	raspi-config

}

function newuser {

	clear
	echo -e "=============== AGREGAR UN USUARIO DE SUDO =============== \n" 
	
	read -r -p "Escribe tu nuevo usuasrio: " SUDOUSER
	adduser "$SUDOUSER"
	usermod -aG sudo victor7w7r

	echo " "
	echo -e "=============== OK =============== \n" 
	read -r -p "Presione Enter para continuar..."
}

function graphical {

	clear
	echo -e "=============== XFCE =============== \n" 
	
	apt install -y xserver-xorg xfce4 xfce4-goodies xfce4-indicator-plugin \
		blueman ttf-ubuntu-font-family firefox nemo cinnamon-l10n gdm3

	touch /root/.xinitrc
	echo 'export XAUTHORITY=${HOME}/.Xauthority' > /root/.xinitrc
	echo 'xfce4-session' >> /root/.xinitrc	

	touch /home/"$SUDOUSER"/.xinitrc
	echo 'export XAUTHORITY=${HOME}/.Xauthority' > /home/"$SUDOUSER"/.xinitrc
	echo 'xfce4-session' >>  /home/"$SUDOUSER"/.xinitrc

	chown "$SUDOUSER" /home/"$SUDOUSER"/.xinitrc

	echo " "
	echo -e "=============== OK =============== \n" 
	read -r -p "Presione Enter para continuar..."

}

function ohmyzsh {

	clear
	echo -e "=============== OMZ =============== \n" 

	touch /home/"$SUDOUSER"/omz.sh

	echo '#!/bin/bash' > /home/"$SUDOUSER"/omz.sh
	echo 'sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"' >> /home/"$SUDOUSER"/omz.sh
	echo 'sed -i -e "s/ZSH_THEME=.*/ZSH_THEME=\"pmcgee\"/" .zshrc' >> /home/"$SUDOUSER"/omz.sh
	echo 'sed -i -e "/^source $ZSH.*/i ZSH_DISABLE_COMPFIX=true" .zshrc' >> /home/"$SUDOUSER"/omz.sh
	echo 'sudo ln -s "$HOME"/.zshrc /root/.zshrc' >> /home/"$SUDOUSER"/omz.sh
	echo 'sudo ln -s "$HOME"/.oh-my-zsh /root/.oh-my-zsh' >> /home/"$SUDOUSER"/omz.sh
	echo 'git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting' >> /home/"$SUDOUSER"/omz.sh
	echo 'git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions' >> /home/"$SUDOUSER"/omz.sh
	echo 'sed -i -e "s/plugins=(.*/plugins=(git zsh-syntax-highlighting zsh-autosuggestions)/" .zshrc' >> /home/"$SUDOUSER"/omz.sh

	chown "$SUDOUSER" /home/"$SUDOUSER"/omz.sh

	echo "Hemos creado un script llamado omz.sh en tu carpeta de home, después de reiniciar, usa chmod +x omz.sh"

	echo " "
	echo -e "=============== OK =============== \n" 
	read -r -p "Presione Enter para continuar..."

}

function software {

	systemctl mask lvm2-monitor

	echo "disable_overscan=1" >> /boot/config.txt
	echo "hdmi_drive=2" >> /boot/config.txt

	dialog --title "Más Sofware!!" --backtitle "036 Creative Studios" \
		--yesno "Este script tiene un pequeño pack de software, ¿Te gusta?\n \
			-> baobab \n \
			-> ntfs-3g \n \
			-> exfat-utils \n \
			-> xrdp \n \
			-> xarchiver \n \
			-> synaptic \n \
			-> neofetch \n \
			-> vlc \n \
			-> gdebi \n \
			-> numix-gtk-theme-git\n \
			-> numix-icon-theme " 26 65
	clear
	response=$?

	if [ $response -eq 0 ]; then

	clear
	echo -e "=============== SOFTWARE =============== \n" 

	sudo apt install -y xrdp gdebi synaptic aptitude neofetch vlc libwnck-common libwnck22 \
		baobab ntfs-3g exfat-fuse exfat-utils xarchiver numix-gtk-theme numix-icon-theme-circle

	adduser xrdp ssl-cert
	sudo systemctl enable xrdp
	sudo systemctl enable xrdp-sesman
	sudo systemctl enable preload

	echo " "
	echo -e "=============== OK =============== \n" 
	read -r -p "Presione Enter para continuar..."

	elif [ $response -eq 1 ]; then
		clear
		return
	else
		clear
		exit 0
	fi
}

function finisher {

	clear
	dialog --msgbox 'LISTO!!!, Tu RPI4 fue configurado exitosamente, si tienes errores, repórtalo a 036raspberry' 7 50
	clear
	echo "Por favor reinicia tu rpi4 para realizar los cambios"
	exit 0
}

core

[ -f $LOCALESTEMP ] && rm $LOCALESTEMP
[ -f $HOSTTEMP ] && rm $HOSTTEMP
[ -f $GRAPHICALTEMP ] && rm $GRAPHICALTEMP